apiVersion: apps/v1
kind: Deployment
metadata:
  name: sops-decrypt-plugin
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sops-decrypt-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sops-decrypt-plugin
    spec:
      initContainers:
        - name: import-gpg-key
          command: [ "/usr/bin/bash", "-c" ]
          args:
          - for i in $(find /sops-gpg -maxdepth 2 -name *.asc -type f -printf "%p\n"); do gpg --import $i; done
          env:
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
          image: quay.io/argoproj/argocd:v2.12.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /sops-gpg
              name: sops-gpg
            - mountPath: /gnupg-home
              name: gnupg-home
      containers:
        - name: main
          image: danieles/sops-decrypt-argocd:0.0.2
          env:
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
          ports:
            - containerPort: 4355
              name: http
          volumeMounts:
            - mountPath: /var/run/argo/token
              name: token
              subPath: token
            - mountPath: /var/run/argo/pgp-key
              name: sops-gpg
            - name: sops-decrypt-script
              mountPath: /app
            - name: gnupg-home
              mountPath: /gnupg-home
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4355
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4355
            initialDelaySeconds: 30
            periodSeconds: 5
      volumes:
        - name: token
          secret:
            secretName: sops-decrypt-token
        - name: sops-gpg
          secret:
            defaultMode: 420
            secretName: argocd-secret
        - name: sops-decrypt-script
          configMap:
            name: sops-decrypt-script
        - emptyDir: {}
          name: gnupg-home