apiVersion: v1
kind: Service
metadata:
  name: sops-decrypt-service
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: sops-decrypt-plugin
  ports:
  - name: http
    port: 80
    targetPort: 4355
