apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myplugin
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - plugin:
        configMapRef:
          name: sops-decrypt
        input:
          parameters:
            key1: "value1"
            key2: "value2"
            list: [ "list", "of", "values" ]
            boolean: true
            map:
              key1: "value1"
              key2: "value2"
              key3: "value3"
  template:
    metadata:
      name: sealed-secret
      namespace: argocd
      annotations:
        fromtemplate: '{{.valuesobject}}'
    spec:
      project: default
      source:
        chart: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.16.1
        helm:
          #releaseName: '{{.valuesobject}}'
          releaseName: sealed-secrets
          values: |
            rateLimit: 3
            rateLimitBurst: 5
      destination:
        server: "https://kubernetes.default.svc"