resources:
  - manifests/applicationset-secret.yaml
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/namespace.yaml
  - manifests/plugin-secret.yaml
  - manifests/service.yaml

configMapGenerator:
  - name: sops-decrypt-script
    namespace: argocd-plugins
    disableNameSuffixHash: true
    files:
      #- main.py=main.py
      - decrypt.go=sops-decrypt/decrypt.go