# This secret lives with the ApplicationSet controller and is referenced from the plugin ConfigMap.
apiVersion: v1
kind: Secret
metadata:
  name: sops-decrypt-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
stringData:
  token: 'supersecret'
